// app/layout.server.tsx
import type { Metadata } from "next";
import RootLayout from "./layout.client";

export const metadata: Metadata = {
  title: "Welcome to my website",
  description: "Generated by create next app",
};

export default function ServerLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <RootLayout>{children}</RootLayout>;
}
