import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import MainNavbar from "@/components/MainNavbar";
import { Flowbite, ThemeModeScript } from "flowbite-react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Welcome to my website",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <ThemeModeScript />
      </head>
      <Flowbite>
        <body
          className={`${inter.className} dark:bg-gray-900 dark:text-white bg-gray-200`}
        >
          <div className="container mx-auto px-2">
            <MainNavbar />
            {children}
          </div>
        </body>
      </Flowbite>
    </html>
  );
}
