import type { Metadata } from "next";
import { Exo } from "next/font/google";
import "./globals.css";
import "animate.css";
import MainNavbar from "@/components/Shared/MainNavbar";
import { Flowbite, ThemeModeScript } from "flowbite-react";
import MainFooter from "@/components/Shared/MainFooter";

const font = Exo({
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Welcome to my website",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <ThemeModeScript />
      </head>
      <body
        className={`${font.className} dark:bg-gray-900 dark:text-white bg-gray-200`}
      >
        <Flowbite>
          <div className="container mx-auto px-2">
            <MainNavbar />
            {children}
            <MainFooter />
          </div>
        </Flowbite>
      </body>
    </html>
  );
}
